services:
  dev-db:
    environment:
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
    image: "postgres:13"
    networks:
      - freecodecamp
    ports:
      - "5434:5432"
networks:
  freecodecamp:
version: "3.8"
